### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by tkellen** [gmarty/grunt-closure-compiler#10]
registerHelpers will be depreciated in grunt 0.4.

To see how helpers will be handled in the future (using standard npm require), check out the following links:
https://github.com/gruntjs/grunt-contrib-uglify/blob/master/tasks/uglify.js#L15
https://github.com/gruntjs/grunt-contrib-uglify/blob/master/tasks/lib/min.js

**Comment by gmarty** [comment]
Hi! Thanks for letting me know.
I fixed this in f13a4eb324eb185011d630fa622c5c82345acb23 and updated the npm package.
