### ISSUE TITLE
Option avoid report.txt file creation

### ISSUE THREAD

**Issue by gkond** [gmarty/grunt-closure-compiler#18]
Kindly consider this small update to add an option to allow avoid .report.txt file creation.

```
    // Check for report file 
    if (typeof data.createReport === 'undefined') {
        data.createReport = true;
    } else {
        data.createReport = false;
    }
```

...

```
    if(data.createReport) {
      // Write compile report to a file.
      fs.writeFile(reportFile, stderr, function(err) {
        if (err) {
          grunt.warn(err);
          done(false);
        }

        grunt.log.writeln('A report is saved in ' + reportFile + '.');
        done();
      });
    }
```

**Comment by reintroducing** [comment]
+1. these files are extremely annoying and usually just blank txt files. this would be a very welcome addition.

**Comment by reintroducing** [comment]
foot in mouth yet again. just saw noreport: true in the other PR. @gkond you can close this issue and refer to https://github.com/gmarty/grunt-closure-compiler/pull/28
