### ISSUE TITLE
Externs option is not recognized

### ISSUE THREAD

**Issue by gkond** [gmarty/grunt-closure-compiler#21]
Task ends with message:
Process finished with exit code 3 ("Task error")

It seems that you need to replace calls:
grunt.file.expandFiles()
with:
grunt.file.expand()

Grunt 0.4.0 has no expandFiles: https://github.com/gruntjs/grunt/wiki/grunt.file

**Comment by gmarty** [comment]
Fixed in v.0.0.17.
