### ISSUE TITLE
specify relative path to compiler jar?

### ISSUE THREAD

**Issue by paulirish** [gmarty/grunt-closure-compiler#3]
Can I specify a path to the compiler jar in the options instead?
This works better for a project where I have multiple contributors and I dont want to have them set up ENV variables on all their machines

**Comment by gmarty** [comment]
Hi Paul! Thx for this issue.

Would you be OK with the following behavior?
First, the task looks for a path to the install dir of Closure Compiler in the options.
Then, it looks for a path in env variables.

Doing so makes it easy to point to the files located in contrib/externs folder of Closure Compiler right from the Grunt config without specifying the full path to them.

**Comment by paulirish** [comment]
Yeah that sounds awesome.

**Comment by gmarty** [comment]
In the latest version, you can specify a path to Closure Compiler directory right from the Grunt tasks using the `ClosurePath` property. No need to set up an env var anymore!

``` javascript
grunt.initConfig({
  'closure-compiler': {
    frontend: {
      closurePath: '/src/to/closure-compiler',
      js: 'static/src/frontend.js',
      jsOutputFile: 'static/js/frontend.min.js',
      options: {
        compilation_level: 'ADVANCED_OPTIMIZATIONS',
        language_in: 'ECMASCRIPT5_STRICT'
      }
    }
  }
});
```

**Comment by paulirish** [comment]
Woohoo! Nice work!
