### ISSUE TITLE
Command failed: java.io.FileNotFoundException

### ISSUE THREAD

**Issue by AlexeyAndKartashov** [gmarty/grunt-closure-compiler#39]
Hi!
I started use this package with this config:

```
'closure-compiler': {
    scripts: {
        closurePath     : 'js/helpers/closure-compiler/',
        js              : 'js/scripts.js',
        jsOutputFile    : 'js/scripts.min.js',
        options: {
            compilation_level: 'SIMPLE_OPTIMIZATIONS'
        }
    }
}
```

But getting error:
'Warning: Command failed: java.io.FileNotFoundException:path\to\file\scripts.min.js'
![preent screen](https://f.cloud.github.com/assets/2387592/1461502/95efcf8a-44b5-11e3-8341-c2c7efa25781.png)

Minified target file is created but is empty..

Any ideas how can I overcome this?

**Comment by gmarty** [comment]
It's not related to this Grunt task. It seems to me that Java can't create the file to output, possibly because of the `???` in the path.

Sorry, I can't really help.

**Comment by AlexeyAndKartashov** [comment]
Ok, thanks!
